# Project information
site_name: readDiag
site_author: Grupo de Assimilação de Dados (GAD-DIMNT-CPTEC)
site_description: A Python class to access, read and plot information from diagnostic files from the GSI (Gridpoint Statistical Interpolation)

# Repository
repo_name: GAD-DIMNT-CPTEC/readDiag
repo_url: https://github.com/GAD-DIMNT-CPTEC/readDiag
edit_uri: edit/master/docs/  

# Page tree
nav:
  - English:
    - index.md
    - Installation: 
      - Local: en/install_local.md
      - Remote: en/install_remote.md
    - Aplication:
      - Introduction: en/intro.md
      - Usage: en/usage.md
  - Português:
    - readDiag: pt/index.md
    - Instalação:
      - Local: pt/instala_local.md
      - Remoto: pt/instala_remoto.md
    - Aplicação:
      - Introdução: pt/intro.md
      - Uso: pt/uso.md

#Configuration
theme: 
  name: material
  language: pt-BR
  palette:
    primary: teal
    accent: teal
  features:
#    - content.tabs.link
#    - navigation.instant
#    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.sections
#    - navigation.top
#  name: readthedocs
#  palette:
#    scheme: slate

extra:
    social:
      #- icon: fontawesome/brands/youtube
      #  link: https://www.youtube.com/channel/UCYtOSAm2NlYArmPwUkg1kUw
      - icon: fontawesome/brands/github
        link: https://github.com/joaogerd
      - icon: fontawesome/solid/paper-plane
        link: mailto:joao.gerd@inpe.com

# Extensions
markdown_extensions:
  - footnotes
  - tables
  - admonition
  - abbr
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

# Plugins
plugins:
  - mkdocs-video
  - search
#  - pdf-export
#  - mkpdfs
